version: '3.8'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8.0'
    container_name: 'zookeeper_ambev'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network

  kafka:
    image: 'bitnami/kafka:3.3.2'
    container_name: 'kafka_ambev'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app-network
    depends_on:
      - zookeeper

  postgres:
    container_name: postgres_ambev
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      retries: 10
      start_period: 40s
      timeout: 5s
    command: >
      bash -c "docker-entrypoint.sh postgres & sleep 5 && \
      psql -U root -tc \"SELECT 1 FROM pg_database WHERE datname = 'order_db'\" | grep -q 1 || psql -U root -c 'CREATE DATABASE order_db;' && \
      psql -U root -tc \"SELECT 1 FROM pg_database WHERE datname = 'product_db'\" | grep -q 1 || psql -U root -c 'CREATE DATABASE product_db;' && \
      wait"

  order_service:
    container_name: order_service
    hostname: order-service
    build: order-service/.
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_ORDER_TOPIC: order-topic
      KAFKA_ORDER_GROUP: order-group
      KAFKA_PRODUCT_TOPIC: product-topic
      KAFKA_PRODUCT_GROUP: product-group
    volumes:
      - ../:/order_service
    networks:
      - app-network
    depends_on:
      - postgres
      - zookeeper
      - kafka
      - product_service

  product_service:
    container_name: product_service
    hostname: product-service
    build: product-service/.
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ../:/product_service
    networks:
      - app-network
    depends_on:
      - postgres
      - zookeeper
      - kafka

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
