services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8.0'
    container_name: 'zookeeper_ambev'
    hostname: 'zookeeper'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network
    
  kafka:
    image: 'bitnami/kafka:3.3.2'
    container_name: 'kafka_ambev'
    hostname: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app-network
    depends_on:
      - zookeeper

  mysql:
    container_name: mysql_ambev
    image: mysql:8.4.2
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: prova_ambev
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  order_service:
    container_name: order_service
    hostname: 127.0.0.1
    build: order-service/.
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_ORDER_TOPIC: order-topic
      KAFKA_ORDER_GROUP: order-group
      KAFKA_PRODUCT_TOPIC: product-topic
      KAFKA_PRODUCT_GROUP: product-group
    volumes:
      - ../:/order_service
    networks:
      - app-network
    depends_on:
      - mysql
      - zookeeper
      - kafka

  product_service:
    container_name: product_service
    hostname: 127.0.0.1
    build: product-service/.
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ../:/product_service
    networks:
      - app-network
    depends_on:
      - mysql
      - zookeeper
      - kafka

volumes:
  mysql-data:
networks:
  app-network:
    driver: bridge
